ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER tm_admin IDENTIFIED BY admin1234;

ALTER USER tm_admin DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

GRANT CONNECT, RESOURCE, CREATE VIEW TO tm_admin;

-- 1. MEMBER(회원) 테이블 생성
CREATE TABLE "MEMBER" (
   "MEMBER_NO"   NUMBER   PRIMARY KEY,
   "MEMBER_ID"   VARCHAR2(30) NOT NULL,
   "MEMBER_PW"   VARCHAR2(30) NOT NULL,
   "MEMBER_NM"   VARCHAR2(20) NOT NULL,
   "MEMBER_NICK"   VARCHAR2(30) NOT NULL,
   "PROFILE_IMG"   VARCHAR2(200),
   "MEMBER_ADDR"   VARCHAR2(500),
   "MEMBER_THM"    VARCHAR2(200),
   "MEMBER_Q"    NUMBER NOT NULL,
   "MEMBER_A"    VARCHAR2(200) NOT NULL,
   "ENROLL_DT"   DATE DEFAULT SYSDATE,
   "SECESSION_FL"   CHAR(1)   DEFAULT 'N'
);


COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NM" IS '회원 이름';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICK" IS '회원 닉네임(중복x)';
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '회원 프로필 이미지';
COMMENT ON COLUMN "MEMBER"."MEMBER_ADDR" IS '회원 주소';
COMMENT ON COLUMN "MEMBER"."MEMBER_THM" IS '회원 선호 테마';
COMMENT ON COLUMN "MEMBER"."MEMBER_Q" IS '회원 아이디, 비밀번호 찾기 질문';
COMMENT ON COLUMN "MEMBER"."MEMBER_A" IS '회원 아이디, 비밀번호 찾기 답변';
COMMENT ON COLUMN "MEMBER"."ENROLL_DT" IS '회원 가입일';
COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴여부(Y:탈퇴, N:미탈퇴)';

CREATE SEQUENCE SEQ_MEMBER_NO;

-- 회원 샘플 데이터 삽입
INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01!', '유저일', 
    '유저일', NULL, '04540,,서울특별시 강남구 테헤란로 14길 6,,5층',
     NULL, 1, 'KH정보교육원', DEFAULT, DEFAULT);
     
--------------------------------------------------------------------------------
     
-- 2. 게시판 테이블
CREATE TABLE BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(200) NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    READ_COUNT NUMBER DEFAULT 0,
    MEMBER_NO NUMBER REFERENCES MEMBER -- MEMBER 테이블 PK값 참조
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '게시글 작성일';
COMMENT ON COLUMN BOARD.READ_COUNT IS '조회수';
COMMENT ON COLUMN BOARD.MEMBER_NO IS '회원 번호(작성자)';

CREATE SEQUENCE SEQ_BOARD_NO;

-- BOARD 테이블 샘플 데이터
INSERT INTO BOARD 
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글 1', '샘플1 내용입니다.', DEFAULT, DEFAULT, 1);

INSERT INTO BOARD 
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글 2', '샘플2 내용입니다.', DEFAULT, DEFAULT, 1);

INSERT INTO BOARD 
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글 3', '샘플3 내용입니다.', DEFAULT, DEFAULT, 1);

--------------------------------------------------------------------------------

-- 3. 댓글 테이블
CREATE TABLE REPLY(
    REPLY_NO NUMBER PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(500) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    MEMBER_NO NUMBER REFERENCES MEMBER, -- MEMBER 테이블 PK 참조
    BOARD_NO NUMBER REFERENCES BOARD -- BOARD 테이블 PK 참조
);

COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글 번호(PK)';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글 내용';
COMMENT ON COLUMN REPLY.CREATE_DATE IS '댓글 작성일';
COMMENT ON COLUMN REPLY.MEMBER_NO IS '회원 번호(작성자)';
COMMENT ON COLUMN REPLY.BOARD_NO IS '게시글 번호(어떤 게시글의 댓글인지 확인)';

CREATE SEQUENCE SEQ_REPLY_NO;

-- 댓글 샘플 데이터 삽입
-- REPLY_NO, REPLY_CONTENT, CREATE_DATE, MEMBER_NO, BOARD_NO
INSERT INTO REPLY
VALUES(SEQ_REPLY_NO.NEXTVAL, '샘플1의 댓글1', DEFAULT, 1, 1);

INSERT INTO REPLY
VALUES(SEQ_REPLY_NO.NEXTVAL, '샘플1의 댓글2', DEFAULT, 1, 1);

INSERT INTO REPLY
VALUES(SEQ_REPLY_NO.NEXTVAL, '샘플1의 댓글3', DEFAULT, 1, 1);

--------------------------------------------------------------------------------

-- 회원 샘플 데이터 추가 삽입
INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02', 'pass02!', '유저이', 
    '유저이', NULL, '04540,,서울특별시 강남구 테헤란로 14길 6,,5층',
     NULL, 2, 'KH정보교육원', DEFAULT, DEFAULT);
     
INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user03', 'pass03!', '유저삼', 
    '유저삼', NULL, '04540,,서울특별시 강남구 테헤란로 14길 6,,5층',
     NULL, 2, 'KH정보교육원', DEFAULT, DEFAULT);
     
INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user04', 'pass04!', '유저사', 
    '유저사', NULL, '04540,,서울특별시 강남구 테헤란로 14길 6,,5층',
     NULL, 2, 'KH정보교육원', DEFAULT, DEFAULT);
     
INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user05', 'pass05!', '유저오', 
    '유저오', NULL, '04540,,서울특별시 강남구 테헤란로 14길 6,,5층',
     NULL, 2, 'KH정보교육원', DEFAULT, DEFAULT);
     
INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user06', 'pass06!', '유저육', 
    '유저육', NULL, '04540,,서울특별시 강남구 테헤란로 14길 6,,5층',
     NULL, 2, 'KH정보교육원', DEFAULT, DEFAULT);